### ISSUE TITLE
Testing for installation

### ISSUE THREAD

**Issue by rborn** [alvelig/react-native-maps-pods-example#1]
✅ Debug mode - RN 0.51 `react-native run-ios`
✅ Release mode on device - RN 0.51 `react-native run-ios --device --configuration Release`
✅ `Xcode -> Product -> Archive` and install on device
✅ Other versions of ReactNative (as the instructions specify 0.49) `tested with 0.51`
✅ Test for new project and already setup one with more native modules
✅ Testflight

**Comment by rborn** [comment]
@alvelig could you please point me to where I could find more info about RN > 49 having issues with the pods as you state in readme? Thanks

**Comment by alvelig** [comment]
I had error like this: https://github.com/expo/expo/issues/923

**Comment by rborn** [comment]
@alvelig so you were using an expo ejected app and not one created by `react-native init` ?

**Comment by alvelig** [comment]
No, that's just a similar error. No expo. Just `react-native init` and then followed README.MD

**Comment by rborn** [comment]
Ok, thanks

**Comment by rborn** [comment]
@alvelig did some tests, preparing the archive  won't compile.
~~~
Ld build/Build/Intermediates/ArchiveIntermediates/reactNativeMapsExample/IntermediateBuildFilesPath/reactNativeMapsExample.build/Release-iphoneos/reactNativeMapsExample.build/Objects-normal/arm64/reactNativeMapsExample normal arm64
ld: 459 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~
I'm looking for a workaround and let you know if I manage

**Comment by rborn** [comment]
@alvelig I tried to remove `s.dependency 'React'` from podspec files, same result, it won't compile for archiving 😟

**Comment by rborn** [comment]
@alvelig I might have found a way, I'll make a PR after few more tests (I need to see if it will work with other native modules not only standalone) 😊

**Comment by rborn** [comment]
@alvelig I managed to archive another project with more native modules in it and it worked. I installed the archived build on my device and worked fine but I want to make a testflight upload to see if there will work too (I had issues where the app won't load)
Once the testflight is ok I'll make a PR.

Thanks for all the support :)

**Comment by rborn** [comment]
still waiting for the testflight review to be done by Apple 😞

**Comment by rborn** [comment]
All passed, testflight runs just fine 🎉
